// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package discogsserver is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	ReleaseMetadata
	Empty
	FolderList
	ReleaseList
	ReleaseMove
	MetadataUpdate
*/
package discogsserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import godiscogs "github.com/brotherlogic/godiscogs"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReleaseMetadata struct {
	// The date the release was added
	DateAdded int64 `protobuf:"varint,1,opt,name=date_added,json=dateAdded" json:"date_added,omitempty"`
	// The date the release was last refreshed
	DateRefreshed int64 `protobuf:"varint,2,opt,name=date_refreshed,json=dateRefreshed" json:"date_refreshed,omitempty"`
	// The path to the file on iTunes if available
	FilePath string `protobuf:"bytes,3,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	// The cost of the record in pence
	Cost int32 `protobuf:"varint,4,opt,name=cost" json:"cost,omitempty"`
}

func (m *ReleaseMetadata) Reset()                    { *m = ReleaseMetadata{} }
func (m *ReleaseMetadata) String() string            { return proto.CompactTextString(m) }
func (*ReleaseMetadata) ProtoMessage()               {}
func (*ReleaseMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FolderList struct {
	Folders []*godiscogs.Folder `protobuf:"bytes,1,rep,name=folders" json:"folders,omitempty"`
}

func (m *FolderList) Reset()                    { *m = FolderList{} }
func (m *FolderList) String() string            { return proto.CompactTextString(m) }
func (*FolderList) ProtoMessage()               {}
func (*FolderList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FolderList) GetFolders() []*godiscogs.Folder {
	if m != nil {
		return m.Folders
	}
	return nil
}

type ReleaseList struct {
	Releases []*godiscogs.Release `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *ReleaseList) Reset()                    { *m = ReleaseList{} }
func (m *ReleaseList) String() string            { return proto.CompactTextString(m) }
func (*ReleaseList) ProtoMessage()               {}
func (*ReleaseList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReleaseList) GetReleases() []*godiscogs.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

type ReleaseMove struct {
	Release     *godiscogs.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	NewFolderId int32              `protobuf:"varint,2,opt,name=new_folder_id,json=newFolderId" json:"new_folder_id,omitempty"`
}

func (m *ReleaseMove) Reset()                    { *m = ReleaseMove{} }
func (m *ReleaseMove) String() string            { return proto.CompactTextString(m) }
func (*ReleaseMove) ProtoMessage()               {}
func (*ReleaseMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReleaseMove) GetRelease() *godiscogs.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type MetadataUpdate struct {
	Release *godiscogs.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	Update  *ReleaseMetadata   `protobuf:"bytes,2,opt,name=update" json:"update,omitempty"`
}

func (m *MetadataUpdate) Reset()                    { *m = MetadataUpdate{} }
func (m *MetadataUpdate) String() string            { return proto.CompactTextString(m) }
func (*MetadataUpdate) ProtoMessage()               {}
func (*MetadataUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MetadataUpdate) GetRelease() *godiscogs.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *MetadataUpdate) GetUpdate() *ReleaseMetadata {
	if m != nil {
		return m.Update
	}
	return nil
}

func init() {
	proto.RegisterType((*ReleaseMetadata)(nil), "discogsserver.ReleaseMetadata")
	proto.RegisterType((*Empty)(nil), "discogsserver.Empty")
	proto.RegisterType((*FolderList)(nil), "discogsserver.FolderList")
	proto.RegisterType((*ReleaseList)(nil), "discogsserver.ReleaseList")
	proto.RegisterType((*ReleaseMove)(nil), "discogsserver.ReleaseMove")
	proto.RegisterType((*MetadataUpdate)(nil), "discogsserver.MetadataUpdate")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for DiscogsService service

type DiscogsServiceClient interface {
	GetCollection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReleaseList, error)
	GetReleasesInFolder(ctx context.Context, in *FolderList, opts ...grpc.CallOption) (*ReleaseList, error)
	MoveToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error)
	AddToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error)
	UpdateMetadata(ctx context.Context, in *MetadataUpdate, opts ...grpc.CallOption) (*ReleaseMetadata, error)
	GetMetadata(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*ReleaseMetadata, error)
	UpdateRating(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*Empty, error)
	GetSingleRelease(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*godiscogs.Release, error)
}

type discogsServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscogsServiceClient(cc *grpc.ClientConn) DiscogsServiceClient {
	return &discogsServiceClient{cc}
}

func (c *discogsServiceClient) GetCollection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReleaseList, error) {
	out := new(ReleaseList)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/GetCollection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) GetReleasesInFolder(ctx context.Context, in *FolderList, opts ...grpc.CallOption) (*ReleaseList, error) {
	out := new(ReleaseList)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/GetReleasesInFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) MoveToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/MoveToFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) AddToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/AddToFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) UpdateMetadata(ctx context.Context, in *MetadataUpdate, opts ...grpc.CallOption) (*ReleaseMetadata, error) {
	out := new(ReleaseMetadata)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/UpdateMetadata", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) GetMetadata(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*ReleaseMetadata, error) {
	out := new(ReleaseMetadata)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/GetMetadata", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) UpdateRating(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/UpdateRating", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) GetSingleRelease(ctx context.Context, in *godiscogs.Release, opts ...grpc.CallOption) (*godiscogs.Release, error) {
	out := new(godiscogs.Release)
	err := grpc.Invoke(ctx, "/discogsserver.DiscogsService/GetSingleRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscogsService service

type DiscogsServiceServer interface {
	GetCollection(context.Context, *Empty) (*ReleaseList, error)
	GetReleasesInFolder(context.Context, *FolderList) (*ReleaseList, error)
	MoveToFolder(context.Context, *ReleaseMove) (*Empty, error)
	AddToFolder(context.Context, *ReleaseMove) (*Empty, error)
	UpdateMetadata(context.Context, *MetadataUpdate) (*ReleaseMetadata, error)
	GetMetadata(context.Context, *godiscogs.Release) (*ReleaseMetadata, error)
	UpdateRating(context.Context, *godiscogs.Release) (*Empty, error)
	GetSingleRelease(context.Context, *godiscogs.Release) (*godiscogs.Release, error)
}

func RegisterDiscogsServiceServer(s *grpc.Server, srv DiscogsServiceServer) {
	s.RegisterService(&_DiscogsService_serviceDesc, srv)
}

func _DiscogsService_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/GetCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).GetCollection(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_GetReleasesInFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FolderList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).GetReleasesInFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/GetReleasesInFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).GetReleasesInFolder(ctx, req.(*FolderList))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_MoveToFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseMove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).MoveToFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/MoveToFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).MoveToFolder(ctx, req.(*ReleaseMove))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_AddToFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseMove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).AddToFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/AddToFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).AddToFolder(ctx, req.(*ReleaseMove))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_UpdateMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).UpdateMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/UpdateMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).UpdateMetadata(ctx, req.(*MetadataUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(godiscogs.Release)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).GetMetadata(ctx, req.(*godiscogs.Release))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_UpdateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(godiscogs.Release)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).UpdateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/UpdateRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).UpdateRating(ctx, req.(*godiscogs.Release))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_GetSingleRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(godiscogs.Release)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).GetSingleRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discogsserver.DiscogsService/GetSingleRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).GetSingleRelease(ctx, req.(*godiscogs.Release))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscogsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discogsserver.DiscogsService",
	HandlerType: (*DiscogsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCollection",
			Handler:    _DiscogsService_GetCollection_Handler,
		},
		{
			MethodName: "GetReleasesInFolder",
			Handler:    _DiscogsService_GetReleasesInFolder_Handler,
		},
		{
			MethodName: "MoveToFolder",
			Handler:    _DiscogsService_MoveToFolder_Handler,
		},
		{
			MethodName: "AddToFolder",
			Handler:    _DiscogsService_AddToFolder_Handler,
		},
		{
			MethodName: "UpdateMetadata",
			Handler:    _DiscogsService_UpdateMetadata_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _DiscogsService_GetMetadata_Handler,
		},
		{
			MethodName: "UpdateRating",
			Handler:    _DiscogsService_UpdateRating_Handler,
		},
		{
			MethodName: "GetSingleRelease",
			Handler:    _DiscogsService_GetSingleRelease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0xb7, 0xb6, 0xdd, 0x6e, 0x4f, 0xda, 0xaa, 0xa3, 0x17, 0x35, 0xa2, 0xc8, 0x80, 0xb0,
	0xa0, 0x64, 0xb1, 0x82, 0xa0, 0xe8, 0xc5, 0x5a, 0xff, 0xb0, 0xe0, 0x8a, 0xce, 0xea, 0x75, 0x48,
	0x93, 0xd3, 0x74, 0x20, 0xdb, 0x29, 0x99, 0xd9, 0x8a, 0x6f, 0xe0, 0x53, 0xf9, 0x6c, 0x9e, 0xcc,
	0x24, 0xad, 0x1b, 0xb2, 0x54, 0xd9, 0xab, 0x66, 0xbe, 0xfc, 0xbe, 0x6f, 0xce, 0x9c, 0x33, 0x0d,
	0x0c, 0x34, 0xe6, 0x6b, 0xcc, 0x83, 0x55, 0xae, 0x8c, 0x62, 0xc3, 0x44, 0xea, 0x58, 0xa5, 0xda,
	0x89, 0xfe, 0xb3, 0x54, 0x9a, 0xc5, 0xc5, 0x2c, 0x88, 0xd5, 0xf9, 0xd1, 0x8c, 0x80, 0x05, 0xe6,
	0x99, 0x4a, 0x65, 0x7c, 0x94, 0xaa, 0x12, 0xdc, 0x3e, 0xb9, 0x04, 0xfe, 0xab, 0x05, 0x37, 0x05,
	0x66, 0x18, 0x69, 0x3c, 0x45, 0x13, 0x25, 0x91, 0x89, 0xd8, 0x03, 0x00, 0xfa, 0xc5, 0x30, 0x4a,
	0x12, 0x4c, 0xc6, 0xad, 0x47, 0xad, 0xc3, 0xb6, 0xe8, 0x17, 0xca, 0x71, 0x21, 0xb0, 0xc7, 0x30,
	0xb2, 0xaf, 0x73, 0x9c, 0xe7, 0xa8, 0x17, 0x84, 0xdc, 0xb0, 0xc8, 0xb0, 0x50, 0x45, 0x25, 0xb2,
	0xfb, 0xd0, 0x9f, 0xcb, 0x0c, 0xc3, 0x55, 0x64, 0x16, 0xe3, 0x36, 0x11, 0x7d, 0x71, 0x50, 0x08,
	0x5f, 0x68, 0xcd, 0x18, 0x74, 0x62, 0xa5, 0xcd, 0xb8, 0x43, 0x7a, 0x57, 0xd8, 0x67, 0xde, 0x83,
	0xee, 0xfb, 0xf3, 0x95, 0xf9, 0xc9, 0x5f, 0x02, 0x7c, 0x50, 0x59, 0x82, 0xf9, 0x27, 0xa9, 0x0d,
	0x7b, 0x02, 0xbd, 0xb9, 0x5d, 0x69, 0x2a, 0xa5, 0x7d, 0xe8, 0x4d, 0x6e, 0x07, 0xdb, 0x43, 0x38,
	0x4e, 0x54, 0x04, 0x7f, 0x03, 0x5e, 0x79, 0x1a, 0xeb, 0x0d, 0xe0, 0x20, 0x77, 0xcb, 0xca, 0xcc,
	0xfe, 0x32, 0x97, 0xa4, 0xd8, 0x30, 0x3c, 0xdc, 0xd8, 0x4f, 0xd5, 0x1a, 0xd9, 0x53, 0xe8, 0x95,
	0xaf, 0x6c, 0x17, 0x9a, 0xdd, 0x15, 0xc2, 0x38, 0x0c, 0x97, 0xf8, 0x23, 0x74, 0xa5, 0x84, 0xd2,
	0xb5, 0xa5, 0x2b, 0x3c, 0x12, 0x5d, 0x99, 0x27, 0x09, 0x5f, 0xc3, 0xa8, 0x6a, 0xf3, 0xf7, 0x55,
	0xd1, 0xaf, 0xff, 0xdc, 0xe3, 0x05, 0xec, 0x5f, 0x58, 0x9f, 0x0d, 0xf7, 0x26, 0x0f, 0x83, 0x4b,
	0x37, 0x20, 0xa8, 0x8d, 0x52, 0x94, 0xf4, 0xe4, 0x77, 0x07, 0x46, 0xef, 0x1c, 0x79, 0x46, 0xa4,
	0x8c, 0x91, 0x4d, 0x61, 0xf8, 0x11, 0xcd, 0x54, 0x65, 0x19, 0xc6, 0x46, 0xaa, 0x25, 0xbb, 0x5b,
	0xcb, 0xb2, 0xc3, 0xf0, 0xfd, 0xe6, 0x1d, 0x8a, 0xf6, 0xf2, 0x3d, 0xf6, 0x19, 0xee, 0x50, 0x48,
	0xa9, 0xe9, 0x93, 0xa5, 0x3b, 0x28, 0xbb, 0x57, 0x33, 0x6d, 0xc7, 0xb9, 0x23, 0xef, 0x2d, 0x0c,
	0x8a, 0xce, 0x7f, 0x53, 0x65, 0xd0, 0x15, 0x74, 0xc1, 0xf8, 0x8d, 0xf5, 0x52, 0xc6, 0x31, 0x78,
	0x74, 0x51, 0xaf, 0x15, 0xf1, 0x15, 0x46, 0x6e, 0x3c, 0xdb, 0xff, 0x44, 0x8d, 0xbc, 0x3c, 0x45,
	0x7f, 0xc7, 0x1c, 0x28, 0x72, 0x0a, 0x1e, 0x75, 0x6a, 0x93, 0xd7, 0x30, 0xe5, 0x7f, 0x08, 0x79,
	0x05, 0x03, 0xb7, 0xa1, 0x88, 0x8c, 0x5c, 0xa6, 0x8d, 0x29, 0x57, 0x9d, 0xe9, 0x35, 0xdc, 0xa2,
	0x02, 0xce, 0xc8, 0x96, 0x61, 0xc9, 0x36, 0xfa, 0x1b, 0x34, 0xbe, 0x37, 0xdb, 0xb7, 0x9f, 0x8b,
	0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x8f, 0x8f, 0x22, 0x80, 0x04, 0x00, 0x00,
}
