// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	ReleaseMetadata
	Empty
	FolderList
	ReleaseList
	ReleaseMove
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import godiscogs "github.com/brotherlogic/godiscogs"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReleaseMetadata struct {
	// The date the release was added
	DateAdded int64 `protobuf:"varint,1,opt,name=date_added,json=dateAdded" json:"date_added,omitempty"`
	// The date the release was last refreshed
	DateRefreshed int64 `protobuf:"varint,2,opt,name=date_refreshed,json=dateRefreshed" json:"date_refreshed,omitempty"`
}

func (m *ReleaseMetadata) Reset()                    { *m = ReleaseMetadata{} }
func (m *ReleaseMetadata) String() string            { return proto.CompactTextString(m) }
func (*ReleaseMetadata) ProtoMessage()               {}
func (*ReleaseMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FolderList struct {
	Folders []*godiscogs.Folder `protobuf:"bytes,1,rep,name=folders" json:"folders,omitempty"`
}

func (m *FolderList) Reset()                    { *m = FolderList{} }
func (m *FolderList) String() string            { return proto.CompactTextString(m) }
func (*FolderList) ProtoMessage()               {}
func (*FolderList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FolderList) GetFolders() []*godiscogs.Folder {
	if m != nil {
		return m.Folders
	}
	return nil
}

type ReleaseList struct {
	Releases []*godiscogs.Release `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *ReleaseList) Reset()                    { *m = ReleaseList{} }
func (m *ReleaseList) String() string            { return proto.CompactTextString(m) }
func (*ReleaseList) ProtoMessage()               {}
func (*ReleaseList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReleaseList) GetReleases() []*godiscogs.Release {
	if m != nil {
		return m.Releases
	}
	return nil
}

type ReleaseMove struct {
	Release     *godiscogs.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
	NewFolderId int32              `protobuf:"varint,2,opt,name=new_folder_id,json=newFolderId" json:"new_folder_id,omitempty"`
}

func (m *ReleaseMove) Reset()                    { *m = ReleaseMove{} }
func (m *ReleaseMove) String() string            { return proto.CompactTextString(m) }
func (*ReleaseMove) ProtoMessage()               {}
func (*ReleaseMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReleaseMove) GetRelease() *godiscogs.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func init() {
	proto.RegisterType((*ReleaseMetadata)(nil), "ReleaseMetadata")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*FolderList)(nil), "FolderList")
	proto.RegisterType((*ReleaseList)(nil), "ReleaseList")
	proto.RegisterType((*ReleaseMove)(nil), "ReleaseMove")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for DiscogsService service

type DiscogsServiceClient interface {
	GetCollection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReleaseList, error)
	GetReleasesInFolder(ctx context.Context, in *FolderList, opts ...grpc.CallOption) (*ReleaseList, error)
	MoveToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error)
	AddToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error)
}

type discogsServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscogsServiceClient(cc *grpc.ClientConn) DiscogsServiceClient {
	return &discogsServiceClient{cc}
}

func (c *discogsServiceClient) GetCollection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReleaseList, error) {
	out := new(ReleaseList)
	err := grpc.Invoke(ctx, "/DiscogsService/GetCollection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) GetReleasesInFolder(ctx context.Context, in *FolderList, opts ...grpc.CallOption) (*ReleaseList, error) {
	out := new(ReleaseList)
	err := grpc.Invoke(ctx, "/DiscogsService/GetReleasesInFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) MoveToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/DiscogsService/MoveToFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discogsServiceClient) AddToFolder(ctx context.Context, in *ReleaseMove, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/DiscogsService/AddToFolder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscogsService service

type DiscogsServiceServer interface {
	GetCollection(context.Context, *Empty) (*ReleaseList, error)
	GetReleasesInFolder(context.Context, *FolderList) (*ReleaseList, error)
	MoveToFolder(context.Context, *ReleaseMove) (*Empty, error)
	AddToFolder(context.Context, *ReleaseMove) (*Empty, error)
}

func RegisterDiscogsServiceServer(s *grpc.Server, srv DiscogsServiceServer) {
	s.RegisterService(&_DiscogsService_serviceDesc, srv)
}

func _DiscogsService_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DiscogsService/GetCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).GetCollection(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_GetReleasesInFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FolderList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).GetReleasesInFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DiscogsService/GetReleasesInFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).GetReleasesInFolder(ctx, req.(*FolderList))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_MoveToFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseMove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).MoveToFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DiscogsService/MoveToFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).MoveToFolder(ctx, req.(*ReleaseMove))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscogsService_AddToFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseMove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscogsServiceServer).AddToFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DiscogsService/AddToFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscogsServiceServer).AddToFolder(ctx, req.(*ReleaseMove))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscogsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DiscogsService",
	HandlerType: (*DiscogsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCollection",
			Handler:    _DiscogsService_GetCollection_Handler,
		},
		{
			MethodName: "GetReleasesInFolder",
			Handler:    _DiscogsService_GetReleasesInFolder_Handler,
		},
		{
			MethodName: "MoveToFolder",
			Handler:    _DiscogsService_MoveToFolder_Handler,
		},
		{
			MethodName: "AddToFolder",
			Handler:    _DiscogsService_AddToFolder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x4e, 0x3a, 0x31,
	0x14, 0xc5, 0xff, 0xfc, 0x09, 0x0c, 0xde, 0x01, 0x4c, 0xea, 0xc6, 0x90, 0x98, 0x68, 0x23, 0xca,
	0xaa, 0x44, 0x78, 0x02, 0xe3, 0x57, 0x48, 0x64, 0x33, 0x6a, 0x5c, 0x92, 0x61, 0x7a, 0x19, 0x9a,
	0x0c, 0x94, 0xb4, 0x15, 0xe3, 0xbb, 0xf9, 0x70, 0x76, 0xda, 0x0e, 0x90, 0xb8, 0x70, 0x35, 0xd3,
	0xdf, 0x39, 0xa7, 0xbd, 0x1f, 0xd0, 0xd6, 0xa8, 0xb6, 0xa8, 0xd8, 0x46, 0x49, 0x23, 0x7b, 0x37,
	0xb9, 0x30, 0xcb, 0x8f, 0x39, 0xcb, 0xe4, 0x6a, 0x38, 0xb7, 0x64, 0x89, 0xaa, 0x90, 0xb9, 0xc8,
	0x86, 0xb9, 0xe4, 0x42, 0x67, 0x32, 0xd7, 0xfb, 0x3f, 0x1f, 0xa1, 0xef, 0x70, 0x9c, 0x60, 0x81,
	0xa9, 0xc6, 0x29, 0x9a, 0x94, 0xa7, 0x26, 0x25, 0x67, 0x00, 0xf6, 0x8b, 0xb3, 0x94, 0x73, 0xe4,
	0xa7, 0xb5, 0xf3, 0xda, 0xa0, 0x9e, 0x1c, 0x95, 0xe4, 0xb6, 0x04, 0xa4, 0x0f, 0x5d, 0x27, 0x2b,
	0x5c, 0x28, 0xd4, 0x4b, 0x6b, 0xf9, 0xef, 0x2c, 0x9d, 0x92, 0x26, 0x15, 0xa4, 0x11, 0x34, 0x1e,
	0x56, 0x1b, 0xf3, 0x45, 0x87, 0x00, 0x8f, 0xb2, 0xe0, 0xa8, 0x9e, 0x85, 0x36, 0xe4, 0x02, 0xa2,
	0x85, 0x3b, 0x69, 0x7b, 0x73, 0x7d, 0x10, 0x8f, 0x22, 0xe6, 0xd5, 0xa4, 0xe2, 0x74, 0x0c, 0x71,
	0x28, 0xc9, 0x25, 0x2e, 0xa1, 0xa5, 0xfc, 0xb1, 0x8a, 0xb4, 0x58, 0xd0, 0x93, 0x9d, 0x42, 0xdf,
	0x76, 0xa1, 0xa9, 0xdc, 0x22, 0xa1, 0x10, 0x05, 0xc9, 0x35, 0x70, 0x98, 0xa9, 0x04, 0xeb, 0xe9,
	0xac, 0xf1, 0x73, 0xe6, 0x9f, 0x9d, 0x09, 0xdf, 0x47, 0x23, 0x89, 0x2d, 0xf4, 0x25, 0x4d, 0xf8,
	0xe8, 0xbb, 0x06, 0xdd, 0x7b, 0x3f, 0xb0, 0x17, 0x3b, 0x69, 0x91, 0x21, 0xb9, 0x86, 0xce, 0x13,
	0x9a, 0x3b, 0x59, 0x14, 0x98, 0x19, 0x21, 0xd7, 0xa4, 0xc9, 0x5c, 0xa3, 0xbd, 0x36, 0x3b, 0x28,
	0x9b, 0xfe, 0x23, 0x23, 0x38, 0xb1, 0xc6, 0xc0, 0xf4, 0x64, 0xed, 0x2f, 0x25, 0x31, 0xdb, 0x8f,
	0xe3, 0x57, 0xe6, 0x0a, 0xda, 0x65, 0xfd, 0xaf, 0x32, 0x98, 0x77, 0x7a, 0x49, 0x7b, 0xe1, 0x25,
	0xeb, 0xeb, 0x43, 0x6c, 0xb7, 0xf1, 0x97, 0x6d, 0xde, 0x74, 0x4b, 0x1e, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x58, 0x46, 0xe9, 0x4d, 0x27, 0x02, 0x00, 0x00,
}
